### ISSUE TITLE
Not an issue just wanted to say smth

### ISSUE THREAD

**Issue by laurinyev** [Coalregion105/Everytale#1]
Hello, Im lolguy91

Im making an undertale ~~ripoff~~ fangame. 
do you want to help me?
my discord: lolguy91(yk discriminators dont exist anymore)

waiting for your response, lolguy91

**Comment by Coalregion105** [comment]
What is it exactly that you need help with?

**Comment by Coalregion105** [comment]
> Hello, Im lolguy91
> 
> Im making an undertale ~ripoff~ fangame. do you want to help me? my discord: lolguy91(yk discriminators dont exist anymore)
> 
> waiting for your response, lolguy91

What exactly do you need help with?

**Comment by laurinyev** [comment]
just some devs, just text me on discord
